enum PowerupTypes {
	EXTRA_LIFE = 0,
	ENERGY = 1,
	SHIELD_BOOST = 2,
	LASER = 3,

	KEY_BLUE = 4,
	KEY_RED = 5,
	KEY_GOLD = 6,

	MISSILE_1 = 10,
	MISSILE_4 = 11,      // 4-pack MUST follow single missile

	QUAD_FIRE = 12,

	VULCAN_WEAPON = 13,
	SPREADFIRE_WEAPON = 14,
	PLASMA_WEAPON = 15,
	FUSION_WEAPON = 16,
	PROXIMITY_WEAPON = 17,
	SMARTBOMB_WEAPON = 20,
	MEGA_WEAPON = 21,
	VULCAN_AMMO = 22,
	HOMING_AMMO_1 = 18,
	HOMING_AMMO_4 = 19,      // 4-pack MUST follow single missile
	CLOAK = 23,
	TURBO = 24,
	INVULNERABILITY = 25,
	MEGAWOW = 27,

	GAUSS_WEAPON = 28,
	HELIX_WEAPON = 29,
	PHOENIX_WEAPON = 30,
	OMEGA_WEAPON = 31,

	SUPER_LASER = 32,
	FULL_MAP = 33,
	CONVERTER = 34,
	AMMO_RACK = 35,
	AFTERBURNER = 36,
	HEADLIGHT = 37,

	SMISSILE1_1 = 38,
	SMISSILE1_4 = 39,      // 4-pack MUST follow single missile
	GUIDED_MISSILE_1 = 40,
	GUIDED_MISSILE_4 = 41,      // 4-pack MUST follow single missile
	SMART_MINE = 42,
	MERCURY_MISSILE_1 = 43,
	MERCURY_MISSILE_4 = 44,      // 4-pack MUST follow single missile
	EARTHSHAKER_MISSILE = 45,

	FLAG_BLUE = 46,
	FLAG_RED = 47,

	HOARD_ORB = 7,       // use unused slot
}